#!/bin/sh

fail()
{
    echo "FAIL: $1" 1>&2
    [ -d "$TMP_DIR" ] && rm -rf "$TMP_DIR"
    exit 1
}
ls -l /images
TMP_DIR=$(mktemp -d) || fail "Unable to make temporary directory for RPM extraction"
RPM_DIR="$TMP_DIR/rpms"

for image in /images/*; do
    echo "Extracting RPMs from image '$image'"
    mkdir -p "$RPM_DIR" || fail "Can't make RPM output directory"
    /usr/bin/xr-image-extract-rpms --output-dir "$RPM_DIR" "$image" || fail "Error extracting images"

    find "$RPM_DIR" -type f -name "*.rpm" | grep -q '\.rpm$' || fail "No RPMs extracted"
    find "$RPM_DIR" -type f -name "*.rpm" | head -5

    rm -rf "$RPM_DIR"
done

rm -rf "$TMP_DIR"

echo PASS

